### ISSUE TITLE
Some bugs about _C.surface_align

### ISSUE THREAD

**Issue by GuaGod** [yanyan-li/GeoGaussian#6]
Traceback (most recent call last):
  File "/cfs/cfs-1wigq30f/vicjliang/code/GeoGaussian/train.py", line 266, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, sparse_num=args.sparse_num)
  File "/cfs/cfs-1wigq30f/vicjliang/code/GeoGaussian/train.py", line 108, in training
    pair_d_loss, pair_normal_loss = SurfaceAlign()(gaussians.get_xyz,
  File "/data/home/vicjliang/vicjliang/envs/GeoGaussian/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/vicjliang/vicjliang/envs/GeoGaussian/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/home/vicjliang/vicjliang/envs/GeoGaussian/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 51, in forward
    return _surface_align.apply(xyz, xyz_id, rotation, knn_index)
  File "/data/home/vicjliang/vicjliang/envs/GeoGaussian/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/data/home/vicjliang/vicjliang/envs/GeoGaussian/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 20, in forward
    loss_d, loss_normal, binning_buffer, mean_d = _C.surface_align(xyz, xyz_id, rotation, knn_index)
RuntimeError: expected scalar type Int but found Long

Thank you for your attention. There are some bugs, when I run "python train.py -s data/Replica-OFF2 --sparse_num 1".  What should I do?

**Comment by yanyan-li** [comment]
thanks for the issue. we will check it today.

**Comment by ruiqiyan** [comment]
Thank you for the author's work. I have also encountered this issue, and this error message indicates that the tensor type passed to the surface_align function in the diff_gaussianrasterization package does not match. Specifically, the surface_align function expects to receive tensors of type Int, but passes tensors of type Long. Do we need to convert all relevant tensors passed to the surface-aslign function from Long type (torch. int64) to Int type (torch. int32).

**Comment by ruiqiyan** [comment]
> 感谢您的提问。我们今天会检查一下。

Thank you for the author's work. I have also encountered this issue, and this error message indicates that the tensor type passed to the surface_align function in the diff_gaussianrasterization package does not match. Specifically, the surface_align function expects to receive tensors of type Int, but passes tensors of type Long. Do we need to convert all relevant tensors passed to the surface-aslign function from Long type (torch. int64) to Int type (torch. int32).

**Comment by yanyan-li** [comment]
> > 感谢您的提问。我们今天会检查一下。
> 
> Thank you for the author's work. I have also encountered this issue, and this error message indicates that the tensor type passed to the surface_align function in the diff_gaussianrasterization package does not match. Specifically, the surface_align function expects to receive tensors of type Int, but passes tensors of type Long. Do we need to convert all relevant tensors passed to the surface-aslign function from Long type (torch. int64) to Int type (torch. int32).

Thanks for pointing out this issue. It should be caused by different versions of submodules. We are checking this part. Should be fixed very soon.

**Comment by ruiqiyan** [comment]
> > > 谢谢您的提问。我们今天会检查一下。
> > 
> > 
> > 感谢作者的工作。我也遇到了这个问题，这个错误信息表明传递给 diff_gaussianrasterization 包中的surface_align函数的张量类型不匹配。具体来说，surface_align函数期望接收Int类型的张量，但传递的张量类型为Long。我们是否需要将传递给surface-asalign函数的所有相关张量从Long类型（torch.int64）转换为Int类型（torch.int32）。
> 
> 感谢您指出这个问题。这应该是由不同版本的子模块引起的。我们正在检查这部分。应该很快就会修复。
Thank you for your reply. Looking forward to your work.

**Comment by fred-lyu** [comment]
@GuaGod Hi, I think the reason for your problem should be that the default data type of the array object in numpy is different on different computer systems, such as Windows and Ubuntu, when the knn index of open3d is transferred. Could you check the tensor object data type of the data in `scene/aussianModel.py [line: 164]` in the code[#47c2f82](https://github.com/yanyan-li/GeoGaussian/tree/47c2f82f6172b16bbad466aa94f1efb33366e57e)? The expected type should be tensor.int32. If you get tensor.int64 , you need to convert it to tensor.int32 by` data = [torch.tensor(np.array(index, dtype=np.int32)).unsqueeze(0) for index in self._knn_index[k]]`

**Comment by ruiqiyan** [comment]
> @GuaGod Hi, I think the reason for your problem should be that the default data type of the array object in numpy is different on different computer systems, such as Windows and Ubuntu, when the knn index of open3d is transferred. Could you check the tensor object data type of the data in `scene/aussianModel.py [line: 164]` in the code[#47c2f82](https://github.com/yanyan-li/GeoGaussian/tree/47c2f82f6172b16bbad466aa94f1efb33366e57e)? The expected type should be tensor.int32. If you get tensor.int64 , you need to convert it to tensor.int32 by` data = [torch.tensor(np.array(index, dtype=np.int32)).unsqueeze(0) for index in self._knn_index[k]]`
It is in the scene/gaussian_model.py file, and the modified lower 166 lines have an additional parenthesis

**Comment by ruiqiyan** [comment]
> @GuaGod Hi, I think the reason for your problem should be that the default data type of the array object in numpy is different on different computer systems, such as Windows and Ubuntu, when the knn index of open3d is transferred. Could you check the tensor object data type of the data in `scene/aussianModel.py [line: 164]` in the code[#47c2f82](https://github.com/yanyan-li/GeoGaussian/tree/47c2f82f6172b16bbad466aa94f1efb33366e57e)? The expected type should be tensor.int32. If you get tensor.int64 , you need to convert it to tensor.int32 by` data = [torch.tensor(np.array(index, dtype=np.int32)).unsqueeze(0) for index in self._knn_index[k]]`
It is in the scene/gaussian_model.py file, and the 166th line that was modified has an additional parenthesis.

**Comment by ruiqiyan** [comment]
@fred-lyu 我对其进行了修改，发现并没有解决这个问题。我使用的是ubantu系统。

**Comment by ruiqiyan** [comment]
@fred-lyu  ![图片1](https://github.com/user-attachments/assets/799ff630-37b3-42f3-b7b4-6bfbecc8a447)
This is my error

**Comment by fred-lyu** [comment]
When I explicitly changed the input data type to `int64`, this problem occurred. According to the error message, the reason for the error is still expecting `int/int32` data, but the input data is `long/int64`. Can you check the data type of the input `SurfaceAlign()`[train.py:line108](https://github.com/yanyan-li/GeoGaussian/blob/main/train.py) method in debug mode?

**Comment by yanyan-li** [comment]
> @fred-lyu ![图片1](https://private-user-images.githubusercontent.com/93872306/351211780-799ff630-37b3-42f3-b7b4-6bfbecc8a447.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTcyNDksIm5iZiI6MTcyMTgxNjk0OSwicGF0aCI6Ii85Mzg3MjMwNi8zNTEyMTE3ODAtNzk5ZmY2MzAtMzdiMy00MmYzLWI3YjQtNmJmYmVjYzhhNDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDEwMjkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZjQwYmY0NzA1YWViZjg5M2VmN2JkYzFkYWJmMjYzZDQxZjhjMTcxZmRjZWIzM2I0Yzg3MThkZjViZjJkODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5D7W2fkHWIUQCP_j78YGT-pTeZYClOrca2e9hsuRBEw) This is my error

![image](https://github.com/user-attachments/as
![Screenshot 2024-07-24 182931](https://github.com/user-attachments/assets/ee26ea59-8f4f-4423-aaf8-2a42e85c18e3)
sets/f1b1db95-34ed-4a4c-9116-3bd09efb1c86)
Caused by different platforms, the dtypes of parameters are changed. We fix this bug in Ubuntu system.

**Comment by ruiqiyan** [comment]
> > @fred-lyu ![图片1](https://private-user-images.githubusercontent.com/93872306/351211780-799ff630-37b3-42f3-b7b4-6bfbecc8a447.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTcyNDksIm5iZiI6MTcyMTgxNjk0OSwicGF0aCI6Ii85Mzg3MjMwNi8zNTEyMTE3ODAtNzk5ZmY2MzAtMzdiMy00MmYzLWI3YjQtNmJmYmVjYzhhNDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDEwMjkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZjQwYmY0NzA1YWViZjg5M2VmN2JkYzFkYWJmMjYzZDQxZjhjMTcxZmRjZWIzM2I0Yzg3MThkZjViZjJkODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5D7W2fkHWIUQCP_j78YGT-pTeZYClOrca2e9hsuRBEw) This is my error
> 
> ![image](https://github.com/user-attachments/as ![Screenshot 2024-07-24 182931](https://private-user-images.githubusercontent.com/26913401/351679074-ee26ea59-8f4f-4423-aaf8-2a42e85c18e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Nzg3NDQsIm5iZiI6MTcyMTg3ODQ0NCwicGF0aCI6Ii8yNjkxMzQwMS8zNTE2NzkwNzQtZWUyNmVhNTktOGY0Zi00NDIzLWFhZjgtMmE0MmU4NWMxOGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAzMzQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNTI5Y2Q2ZGQ5OGU0OThlN2Y1YTlkZWNhZDU4ZjAyNWQ5Yzg4MDIwODJhOTMzNzk4MjY3MjhjMDNjOTVmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gTJneweE2xePggGfVF2rE3wvqalbZKPiZ23usn835v4) sets/f1b1db95-34ed-4a4c-9116-3bd09efb1c86) Due to different platforms, the data type of the parameter is changed. We have fixed this issue on Ubuntu systems.

Thank you for your great contribution. The updated code can run smoothly.

**Comment by Ben-Garcia-DB-Solutions** [comment]
Potentially related issue?

Traceback (most recent call last):
  File "train.py", line 18, in <module>
    from diff_gaussian_rasterization import SurfaceAlign
ImportError: cannot import name 'SurfaceAlign' from 'diff_gaussian_rasterization' (C:\Users\Ben.Garcia\AppData\Local\anaconda3\envs\gaussian_splatting\lib\site-packages\diff_gaussian_rasterization\__init__.py)

**Comment by fred-lyu** [comment]
@Ben-Garcia-DB-Solutions It seems that the `diff_gaussian_reserisation` library has not been updated correctly. You need to recompile our version of `submodules/diff-gaussian-reserisation` and confirm that it has been updated in your conda environment(`C:\Users\Ben.Garcia\AppData\Local\anaconda3\envs\gaussian_splatting\lib\site-packages\`).
